name: Debug Project Structure

on:
  workflow_dispatch:

jobs:
  debug-list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List entire project structure
        run: |
          echo "Root directory:"
          ls -l
          echo "---------------------------------"
          echo "Listing all files recursively:"
          find .
