name: Run Scraper

on:
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files in scraper directory (debug)
        run: 1s -1 scraper

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: pip install requests beautifulsoup4
          
      - name: Run scraper script
        run: python scraper/scrape-leads.py
